/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "BLUESKY_PASSWORD": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BLUESKY_USERNAME": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Hono": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "LINKEDIN_ACCESS_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LINKEDIN_ORGANISATION_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TELEGRAM_BOT_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TELEGRAM_CHANNEL_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TWITTER_BEARER_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TWITTER_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TWITTER_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
